return {}
-- return {
-- 	"folke/flash.nvim",
-- 	event = "VeryLazy",
-- 	opts = {},
-- 	keys = {
-- 		{
-- 			"e",
-- 			-- "<F19>",
-- 			mode = { "n", "x", "o" },
-- 			function()
-- 				require("flash").jump()
-- 			end,
-- 			desc = "Flash",
-- 		},
-- 		{
-- 			"Ee",
-- 			mode = { "n", "x", "o" },
-- 			function()
-- 				require("flash").treesitter()
-- 			end,
-- 			desc = "Flash Treesitter",
-- 		},
-- 		{
-- 			"EE",
-- 			mode = "o",
-- 			function()
-- 				require("flash").remote()
-- 			end,
-- 			desc = "Remote Flash",
-- 		},
-- 		{
-- 			"R",
-- 			mode = { "o", "x" },
-- 			function()
-- 				require("flash").treesitter_search()
-- 			end,
-- 			desc = "Treesitter Search",
-- 		},
-- 		-- {
-- 		--   "<s-t>",
-- 		--   mode = { "c" },
-- 		--   function()
-- 		--     require("flash").toggle()
-- 		--   end,
-- 		--   desc = "Toggle Flash Search",
-- 		-- },
-- 	},
-- }
